### ISSUE TITLE
[Game CRASH] Game crashes when adding Mysterious Stew to sandwhich

### ISSUE THREAD

**Issue by dumbchi** [FoundationGames/Sandwichable#72] opened 2021-01-17 04:20 UTC
**Description**
The game crashes when I try to add Mysterious Stew to a sandwich

**Crash Log**
[crash-2021-01-16_20.00.35-server.txt](https://github.com/FoundationGames/Sandwichable/files/5825555/crash-2021-01-16_20.00.35-server.txt)

**Comment by FoundationGames** [comment] 2021-01-19 01:14
You are using the 1.1 version of Sandwichable, currently beta releases for 1.2 are available and I would prefer if those releases were tested since many bugs are being fixed in 1.2.

**Comment by FoundationGames** [comment] 2021-01-28 00:48
I was unable to reproduce this bug with _Suspicious Stew_, which I hope is what you were referring to. If I don't recieve more clarification within a week's time, the issue will be closed unresolved. Although, thanks for the contribution.

**Comment by FoundationGames** [comment] 2021-02-05 00:28
Closed due to lack of response or clarification

**Closed as completed by FoundationGames** 2021-02-05 00:28 UTC
Labels: crash

**Comment by Ch1216** [comment] 2022-05-28 03:27
It happens if you get Suspicious Stew from REI and not by not by normal means, Please reopen issue, or should I make another issue?

**Comment by Ch1216** [comment] 2022-06-30 02:36
Since it wasn't reopened or did I get a response I'm going to make a new issue
