### ISSUE TITLE
[Game CRASH] The Sandwiches won't allow me to open my inventory

### ISSUE THREAD

**Issue by KirbyKid256** [FoundationGames/Sandwichable#71] opened 2021-01-12 01:02 UTC
I seem to have a problem with opening the inventory. For some reason, whenever I have this mod installed and open the inventory, my game crashes.

[crash-2021-01-11_20.01.46-client.txt](https://github.com/FoundationGames/Sandwichable/files/5799156/crash-2021-01-11_20.01.46-client.txt)

**Comment by FoundationGames** [comment] 2021-01-13 18:24
OptiFine breaks pretty much any mod which so much as _touches_ rendering code. Please don't use this mod with OptiFine / OptiFabric. If you must use shaders, there's Canvas (which uses its own, new shader format) or an in-development project called Iris which is supposed to be able to load OptiFine shaders, but it's not yet complete and doesn't work with most shaders other than Sildur's. If you need a performance boost, your go-to is Sodium, which does a much better job than OptiFine.

**Comment by FoundationGames** [comment] 2021-01-13 18:25
I just noticed that the issue was being caused by OptiFabric's Sandwichable _Compatibility_ module... likely because I revamped Sandwich rendering in v1.2. I will leave this issue open since it's not a problem with OptiFine, but it is with OptiFabric.

**Comment by FoundationGames** [comment] 2021-01-13 18:28
The reason for the crash is because I renamed a method, and optifabric does not like that.

**Comment by FoundationGames** [comment] 2021-01-28 08:05
Was fixed in the OptiFabric commit above.

**Closed as completed by FoundationGames** 2021-01-28 08:05 UTC
Labels: crash
