### ISSUE TITLE
Issues with registration of items//

### ISSUE THREAD

**Issue by tacogerbil** [FoundationGames/Sandwichable#64] opened 2020-11-25 02:17 UTC
Sorry, I thought I canceled out.. I was called away and didn't have time to fill it in! lol 
1.16.4 
Fabric 10.6 B.214
Fabric API 0.26.3 +1.16
I would normally get a lot of spam coming from Sandwichable.. never made sense until I was working on a crash yesterday (unrelated).   I was using Blame mod to figure out what was crashing the mod and saw it's output also broke out the log spam issue I was having with Sandwichable.  Here's the log output that lays it out :)

https://textbin.net/MwJcuZqrS9

**Comment by FoundationGames** [comment] 2020-11-25 08:23
This issue has no context or additional information. Please help by explaining what the issue is exactly, and I will try to fix it. If I don't get a response I will just close the issue. Anything helps!

**Comment by FoundationGames** [comment] 2020-11-26 00:15
Now that you have edited your comment, I can tell you that this issue has nothing to do with items, it's an issue with configured features that has already been reported in issue #56, by the creator of Blame itself. This issue has also been marked as fixed in development, meaning it's already been fixed for the next update when it releases. If the log spam has to do with the missing texture spam for block models, that is also being worked on. Anyways, thank you for the issue report and I will close this now.

**Closed by FoundationGames** 2020-11-26 00:15 UTC
