### ISSUE TITLE
click one cheese crash, click on two there is no crash

### ISSUE THREAD

**Issue by Miros77** [FoundationGames/Sandwichable#25] opened 2020-06-11 00:02 UTC
Извините я не так подробно описал проблему, click one cheese crash in survival, click cheese on two there is no crash  
fabric-loader-0.7.8+build.184-1.15.2

**Comment by Miros77** [comment] 2020-06-11 00:08
[crash-2020-06-11_02.59.13-client.txt](https://github.com/FoundationGames/Sandwichable/files/4761825/crash-2020-06-11_02.59.13-client.txt)

**Comment by Miros77** [comment] 2020-06-11 00:09
NO OPTIFINE

**Comment by Miros77** [comment] 2020-06-11 00:10
[latest.log](https://github.com/FoundationGames/Sandwichable/files/4761833/latest.log)

**Comment by Miros77** [comment] 2020-06-11 00:11
fabric-api-0.4.32+build.292-1.15

**Comment by Miros77** [comment] 2020-06-11 00:51
the new Fabric and the new Fabric API = CRASH

**Comment by Miros77** [comment] 2020-06-13 00:59
this problem can be solved

**Comment by FoundationGames** [comment] 2020-07-26 22:24
I found the cause, this will be fixed in the next release.

**Comment by FoundationGames** [comment] 2020-07-27 03:05
This has been resolved in the latest commit, stay tuned for version 1.1.2's release!

**Closed by FoundationGames** 2020-07-27 03:05 UTC
